;; -*- lexical-binding: t; -*-
(require 'c-ts-mode)
(require 'cmake-ts-mode)
(require 'csharp-mode)
(require 'css-mode)
(require 'dockerfile-ts-mode)
(require 'elixir-ts-mode)
(require 'go-ts-mode)
(require 'heex-ts-mode)
(require 'html-ts-mode)
(require 'java-ts-mode)
(require 'js)
(require 'json-ts-mode)
(require 'lua-ts-mode)
(require 'markdown-ts-mode)
(require 'mhtml-ts-mode)
(require 'php-ts-mode)
(require 'python)
(require 'ruby-ts-mode)
(require 'rust-ts-mode)
(require 'sh-script)
(require 'toml-ts-mode)
(require 'treesit-x)
(require 'typescript-ts-mode)
(require 'yaml-ts-mode)

(defun print-repo-commit (&optional manifest)
  (set-binary-mode 'stdout t)
  (dolist (source (sort treesit-language-source-alist :key #'car))
    (let* ((id (car source))
           (repo (car (cdr source)))
           (commit (plist-get (cdr (cdr source)) :commit))
           (source-dir (plist-get (cdr (cdr source)) :source-dir)))
       (if manifest
           (princ (format " %s %s" commit id))
         (princ (format "%s %s %s" id repo commit))
         (when source-dir
           (princ " ")
           (princ source-dir)))
      (terpri))))
